/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ClientProvidedEnrichedTransaction : A client-provided transaction that Plaid has enriched.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct ClientProvidedEnrichedTransaction {
    /// The unique ID for the transaction as provided by you in the request.
    #[serde(rename = "id")]
    pub id: String,
    /// The raw description of the transaction.
    #[serde(rename = "description")]
    pub description: String,
    /// The absolute value of the transaction (>= 0)
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<crate::models::EnrichTransactionDirection>,
    /// The ISO-4217 currency code of the transaction e.g. USD.
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: String,
    #[serde(rename = "enrichments")]
    pub enrichments: crate::models::Enrichments,
}

impl ClientProvidedEnrichedTransaction {
    /// A client-provided transaction that Plaid has enriched.
    pub fn new(
        id: String,
        description: String,
        amount: f64,
        iso_currency_code: String,
        enrichments: crate::models::Enrichments,
    ) -> ClientProvidedEnrichedTransaction {
        ClientProvidedEnrichedTransaction {
            id,
            description,
            amount,
            direction: None,
            iso_currency_code,
            enrichments,
        }
    }
}
