/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Counterparty : The counterparty, such as the merchant or financial institution, is extracted by Plaid from the raw description.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct Counterparty {
    /// The name of the counterparty, such as the merchant or the financial institution, as extracted by Plaid from the raw description.
    #[serde(rename = "name")]
    pub name: String,
    /// A unique, stable, Plaid-generated id that maps to the counterparty.
    #[serde(
        rename = "entity_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub entity_id: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: crate::models::CounterpartyType,
    /// The website associated with the counterparty.
    #[serde(rename = "website", deserialize_with = "Option::deserialize")]
    pub website: Option<String>,
    /// The URL of a logo associated with the counterparty, if available. The logo is formatted as a 100x100 pixel PNG file.
    #[serde(rename = "logo_url", deserialize_with = "Option::deserialize")]
    pub logo_url: Option<String>,
}

impl Counterparty {
    /// The counterparty, such as the merchant or financial institution, is extracted by Plaid from the raw description.
    pub fn new(
        name: String,
        r#type: crate::models::CounterpartyType,
        website: Option<String>,
        logo_url: Option<String>,
    ) -> Counterparty {
        Counterparty {
            name,
            entity_id: None,
            r#type,
            website,
            logo_url,
        }
    }
}
