/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacAssetVoe25 : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacAssetVoe25 {
    #[serde(rename = "ASSET_DETAIL")]
    pub asset_detail: crate::models::CreditFreddieMacAssetDetailVoe25,
    #[serde(rename = "ASSET_OWNERS")]
    pub asset_owners: crate::models::AssetOwners,
    #[serde(rename = "ASSET_HOLDER")]
    pub asset_holder: crate::models::AssetHolder,
    #[serde(rename = "ASSET_TRANSACTIONS")]
    pub asset_transactions: crate::models::CreditFreddieMacAssetTransactionsVoe25,
}

impl CreditFreddieMacAssetVoe25 {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(
        asset_detail: crate::models::CreditFreddieMacAssetDetailVoe25,
        asset_owners: crate::models::AssetOwners,
        asset_holder: crate::models::AssetHolder,
        asset_transactions: crate::models::CreditFreddieMacAssetTransactionsVoe25,
    ) -> CreditFreddieMacAssetVoe25 {
        CreditFreddieMacAssetVoe25 {
            asset_detail,
            asset_owners,
            asset_holder,
            asset_transactions,
        }
    }
}
