/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditSessionBankIncomeStatus : The terminal status of the bank income verification.  `APPROVED`: User has approved and verified their income  `NO_DEPOSITS_FOUND`: We attempted, but were unable to find any income in the connected account.  `USER_REPORTED_NO_INCOME`: The user explicitly indicated that they don't receive income in the connected account.

/// The terminal status of the bank income verification.  `APPROVED`: User has approved and verified their income  `NO_DEPOSITS_FOUND`: We attempted, but were unable to find any income in the connected account.  `USER_REPORTED_NO_INCOME`: The user explicitly indicated that they don't receive income in the connected account.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum CreditSessionBankIncomeStatus {
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "NO_DEPOSITS_FOUND")]
    NoDepositsFound,
    #[serde(rename = "USER_REPORTED_NO_INCOME")]
    UserReportedNoIncome,
}

impl ToString for CreditSessionBankIncomeStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Approved => String::from("APPROVED"),
            Self::NoDepositsFound => String::from("NO_DEPOSITS_FOUND"),
            Self::UserReportedNoIncome => String::from("USER_REPORTED_NO_INCOME"),
        }
    }
}

impl Default for CreditSessionBankIncomeStatus {
    fn default() -> CreditSessionBankIncomeStatus {
        Self::Approved
    }
}
