/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieVerificationOfEmploymentVoe25 : Verification of Employment Report

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieVerificationOfEmploymentVoe25 {
    #[serde(rename = "DEAL")]
    pub deal: crate::models::CreditFreddieVerificationOfEmploymentDealVoe25,
    /// The Verification Of Employment (VOE) schema version.
    #[serde(rename = "SchemaVersion")]
    pub schema_version: f32,
}

impl CreditFreddieVerificationOfEmploymentVoe25 {
    /// Verification of Employment Report
    pub fn new(
        deal: crate::models::CreditFreddieVerificationOfEmploymentDealVoe25,
        schema_version: f32,
    ) -> CreditFreddieVerificationOfEmploymentVoe25 {
        CreditFreddieVerificationOfEmploymentVoe25 {
            deal,
            schema_version,
        }
    }
}
