/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacAssetTransactionsVoe25 : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacAssetTransactionsVoe25 {
    #[serde(rename = "ASSET_TRANSACTION")]
    pub asset_transaction: Vec<crate::models::CreditFreddieMacAssetTransactionVoe25>,
}

impl CreditFreddieMacAssetTransactionsVoe25 {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(
        asset_transaction: Vec<crate::models::CreditFreddieMacAssetTransactionVoe25>,
    ) -> CreditFreddieMacAssetTransactionsVoe25 {
        CreditFreddieMacAssetTransactionsVoe25 { asset_transaction }
    }
}
