/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditDocumentMetadata : Object representing metadata pertaining to the document.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditDocumentMetadata {
    /// The name of the document.
    #[serde(rename = "name")]
    pub name: String,
    /// The type of document.  `PAYSTUB`: A paystub.  `BANK_STATEMENT`: A bank statement.  `US_TAX_W2`: A W-2 wage and tax statement provided by a US employer reflecting wages earned by the employee.  `US_MILITARY_ERAS`: An electronic Retirement Account Statement (eRAS) issued by the US military.  `US_MILITARY_LES`: A Leave and Earnings Statement (LES) issued by the US military.  `US_MILITARY_CLES`: A Civilian Leave and Earnings Statment (CLES) issued by the US military.  `GIG`: Used to indicate that the income is related to gig work. Does not necessarily correspond to a specific document type.  `PLAID_GENERATED_PAYSTUB_PDF`: Used to indicate that the PDF for the paystub was generated by Plaid.  `NONE`: Used to indicate that there is no underlying document for the data.  `UNKNOWN`: Document type could not be determined.
    #[serde(rename = "document_type", deserialize_with = "Option::deserialize")]
    pub document_type: Option<String>,
    /// Signed URL to retrieve the underlying file.
    #[serde(rename = "download_url", deserialize_with = "Option::deserialize")]
    pub download_url: Option<String>,
    /// The processing status of the document.
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<String>,
}

impl CreditDocumentMetadata {
    /// Object representing metadata pertaining to the document.
    pub fn new(
        name: String,
        document_type: Option<String>,
        download_url: Option<String>,
        status: Option<String>,
    ) -> CreditDocumentMetadata {
        CreditDocumentMetadata {
            name,
            document_type,
            download_url,
            status,
        }
    }
}
