/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacReportsGetResponse : CreditFreddieMacReportsGetResponse defines the response schema for `/credit/freddie_mac/reports/get`

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacReportsGetResponse {
    #[serde(rename = "VOA")]
    pub voa: crate::models::CreditFreddieMacVerificationOfAssetsVoa24,
    #[serde(
        rename = "VOE",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub voe: Option<Option<crate::models::CreditFreddieVerificationOfEmploymentVoe25>>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CreditFreddieMacReportsGetResponse {
    /// CreditFreddieMacReportsGetResponse defines the response schema for `/credit/freddie_mac/reports/get`
    pub fn new(
        voa: crate::models::CreditFreddieMacVerificationOfAssetsVoa24,
        request_id: String,
    ) -> CreditFreddieMacReportsGetResponse {
        CreditFreddieMacReportsGetResponse {
            voa,
            voe: None,
            request_id,
        }
    }
}
