/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacPartiesVoa24 : A collection of objects that define specific parties to a deal. This includes the direct participating parties, such as borrower and seller and the indirect parties such as the credit report provider.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacPartiesVoa24 {
    #[serde(rename = "PARTY")]
    pub party: Vec<crate::models::CreditFreddieMacPartyVoa24>,
}

impl CreditFreddieMacPartiesVoa24 {
    /// A collection of objects that define specific parties to a deal. This includes the direct participating parties, such as borrower and seller and the indirect parties such as the credit report provider.
    pub fn new(
        party: Vec<crate::models::CreditFreddieMacPartyVoa24>,
    ) -> CreditFreddieMacPartiesVoa24 {
        CreditFreddieMacPartiesVoa24 { party }
    }
}
