/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacLoanIdentifiersVoa24 : Collection of current and previous identifiers for this loan.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacLoanIdentifiersVoa24 {
    #[serde(rename = "LOAN_IDENTIFIER")]
    pub loan_identifier: Vec<crate::models::LoanIdentifier>,
}

impl CreditFreddieMacLoanIdentifiersVoa24 {
    /// Collection of current and previous identifiers for this loan.
    pub fn new(
        loan_identifier: Vec<crate::models::LoanIdentifier>,
    ) -> CreditFreddieMacLoanIdentifiersVoa24 {
        CreditFreddieMacLoanIdentifiersVoa24 { loan_identifier }
    }
}
