/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacVerificationOfAssetsVoa24 : Verification of Assets Report

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacVerificationOfAssetsVoa24 {
    #[serde(rename = "DEAL")]
    pub deal: crate::models::CreditFreddieMacVerificationOfAssetsDealVoa24,
    /// The Verification Of Assets (VOA) schema version.
    #[serde(rename = "SchemaVersion")]
    pub schema_version: f32,
}

impl CreditFreddieMacVerificationOfAssetsVoa24 {
    /// Verification of Assets Report
    pub fn new(
        deal: crate::models::CreditFreddieMacVerificationOfAssetsDealVoa24,
        schema_version: f32,
    ) -> CreditFreddieMacVerificationOfAssetsVoa24 {
        CreditFreddieMacVerificationOfAssetsVoa24 {
            deal,
            schema_version,
        }
    }
}
