/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieVerificationOfEmploymentDealVoe25 : An object representing a Verification of Employment report.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieVerificationOfEmploymentDealVoe25 {
    #[serde(rename = "LOANS")]
    pub loans: crate::models::CreditFreddieMacLoansVoa24,
    #[serde(rename = "PARTIES")]
    pub parties: crate::models::CreditFreddieMacPartiesVoa24,
    #[serde(rename = "SERVICES")]
    pub services: crate::models::CreditFreddieMacServicesVoe25,
}

impl CreditFreddieVerificationOfEmploymentDealVoe25 {
    /// An object representing a Verification of Employment report.
    pub fn new(
        loans: crate::models::CreditFreddieMacLoansVoa24,
        parties: crate::models::CreditFreddieMacPartiesVoa24,
        services: crate::models::CreditFreddieMacServicesVoe25,
    ) -> CreditFreddieVerificationOfEmploymentDealVoe25 {
        CreditFreddieVerificationOfEmploymentDealVoe25 {
            loans,
            parties,
            services,
        }
    }
}
