/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacVerificationOfAssetsDealVoa24 : An object representing an Asset Report with Freddie Mac schema.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacVerificationOfAssetsDealVoa24 {
    #[serde(rename = "LOANS")]
    pub loans: crate::models::CreditFreddieMacLoansVoa24,
    #[serde(rename = "PARTIES")]
    pub parties: crate::models::CreditFreddieMacPartiesVoa24,
    #[serde(rename = "SERVICES")]
    pub services: crate::models::CreditFreddieMacServicesVoa24,
}

impl CreditFreddieMacVerificationOfAssetsDealVoa24 {
    /// An object representing an Asset Report with Freddie Mac schema.
    pub fn new(
        loans: crate::models::CreditFreddieMacLoansVoa24,
        parties: crate::models::CreditFreddieMacPartiesVoa24,
        services: crate::models::CreditFreddieMacServicesVoa24,
    ) -> CreditFreddieMacVerificationOfAssetsDealVoa24 {
        CreditFreddieMacVerificationOfAssetsDealVoa24 {
            loans,
            parties,
            services,
        }
    }
}
