/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacAssetTransactionVoe25 : An object representing...

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacAssetTransactionVoe25 {
    #[serde(rename = "ASSET_TRANSACTION_DETAIL")]
    pub asset_transaction_detail: crate::models::CreditFreddieMacAssetTransactionDetailVoe25,
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    #[serde(rename = "ASSET_TRANSACTION_DESCRIPTION")]
    pub asset_transaction_description: Vec<crate::models::AssetTransactionDescription>,
}

impl CreditFreddieMacAssetTransactionVoe25 {
    /// An object representing...
    pub fn new(
        asset_transaction_detail: crate::models::CreditFreddieMacAssetTransactionDetailVoe25,
        asset_transaction_description: Vec<crate::models::AssetTransactionDescription>,
    ) -> CreditFreddieMacAssetTransactionVoe25 {
        CreditFreddieMacAssetTransactionVoe25 {
            asset_transaction_detail,
            asset_transaction_description,
        }
    }
}
