/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacLoanVoa24 : Information specific to a mortgage loan agreement between one or more borrowers and a mortgage lender.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacLoanVoa24 {
    #[serde(rename = "LOAN_IDENTIFIERS")]
    pub loan_identifiers: crate::models::CreditFreddieMacLoanIdentifiersVoa24,
    /// Type of loan. The value can only be \"SubjectLoan\"
    #[serde(rename = "LoanRoleType")]
    pub loan_role_type: String,
}

impl CreditFreddieMacLoanVoa24 {
    /// Information specific to a mortgage loan agreement between one or more borrowers and a mortgage lender.
    pub fn new(
        loan_identifiers: crate::models::CreditFreddieMacLoanIdentifiersVoa24,
        loan_role_type: String,
    ) -> CreditFreddieMacLoanVoa24 {
        CreditFreddieMacLoanVoa24 {
            loan_identifiers,
            loan_role_type,
        }
    }
}
