/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacLoansVoa24 : A collection of loans that are part of a single deal.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacLoansVoa24 {
    #[serde(rename = "LOAN")]
    pub loan: crate::models::CreditFreddieMacLoanVoa24,
}

impl CreditFreddieMacLoansVoa24 {
    /// A collection of loans that are part of a single deal.
    pub fn new(loan: crate::models::CreditFreddieMacLoanVoa24) -> CreditFreddieMacLoansVoa24 {
        CreditFreddieMacLoansVoa24 { loan }
    }
}
