/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacVerificationOfAssetResponseVoa24 : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacVerificationOfAssetResponseVoa24 {
    #[serde(rename = "ASSETS")]
    pub assets: crate::models::CreditFreddieMacAssetsVoa24,
}

impl CreditFreddieMacVerificationOfAssetResponseVoa24 {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(
        assets: crate::models::CreditFreddieMacAssetsVoa24,
    ) -> CreditFreddieMacVerificationOfAssetResponseVoa24 {
        CreditFreddieMacVerificationOfAssetResponseVoa24 { assets }
    }
}
