/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacAssetVoa24 : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacAssetVoa24 {
    #[serde(rename = "ASSET_DETAIL")]
    pub asset_detail: crate::models::AssetDetail,
    #[serde(rename = "ASSET_OWNERS")]
    pub asset_owners: crate::models::AssetOwners,
    #[serde(rename = "ASSET_HOLDER")]
    pub asset_holder: crate::models::AssetHolder,
    #[serde(rename = "ASSET_TRANSACTIONS")]
    pub asset_transactions: crate::models::CreditFreddieMacAssetTransactionsVoa24,
    #[serde(rename = "VALIDATION_SOURCES")]
    pub validation_sources: crate::models::ValidationSources,
}

impl CreditFreddieMacAssetVoa24 {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(
        asset_detail: crate::models::AssetDetail,
        asset_owners: crate::models::AssetOwners,
        asset_holder: crate::models::AssetHolder,
        asset_transactions: crate::models::CreditFreddieMacAssetTransactionsVoa24,
        validation_sources: crate::models::ValidationSources,
    ) -> CreditFreddieMacAssetVoa24 {
        CreditFreddieMacAssetVoa24 {
            asset_detail,
            asset_owners,
            asset_holder,
            asset_transactions,
            validation_sources,
        }
    }
}
