/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacAssetDetailVoe25 : Details about an asset.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacAssetDetailVoe25 {
    /// A vendor created unique Identifier.
    #[serde(rename = "AssetUniqueIdentifier")]
    pub asset_unique_identifier: String,
    /// A unique alphanumeric string identifying an asset.
    #[serde(rename = "AssetAccountIdentifier")]
    pub asset_account_identifier: String,
    /// Account Report As of Date / Create Date. Format YYYY-MM-DD
    #[serde(rename = "AssetAsOfDate")]
    pub asset_as_of_date: String,
    /// A text description that further defines the Asset. This could be used to describe the shares associated with the stocks, bonds or mutual funds, retirement funds or business owned that the borrower has disclosed (named) as an asset.
    #[serde(rename = "AssetDescription", deserialize_with = "Option::deserialize")]
    pub asset_description: Option<String>,
    #[serde(rename = "AssetType")]
    pub asset_type: crate::models::AssetType,
    /// Additional Asset Decription some examples are Investment Tax-Deferred , Loan, 401K, 403B, Checking, Money Market, Credit Card,ROTH,529,Biller,ROLLOVER,CD,Savings,Investment Taxable, IRA, Mortgage, Line Of Credit.
    #[serde(
        rename = "AssetTypeAdditionalDescription",
        deserialize_with = "Option::deserialize"
    )]
    pub asset_type_additional_description: Option<String>,
    /// The Number of days requested made to the Financial Institution. Example When looking for 3 months of data from the FI, pass in 90 days.
    #[serde(rename = "AssetDaysRequestedCount")]
    pub asset_days_requested_count: i32,
    /// Ownership type of the asset account.
    #[serde(
        rename = "AssetOwnershipType",
        deserialize_with = "Option::deserialize"
    )]
    pub asset_ownership_type: Option<String>,
}

impl CreditFreddieMacAssetDetailVoe25 {
    /// Details about an asset.
    pub fn new(
        asset_unique_identifier: String,
        asset_account_identifier: String,
        asset_as_of_date: String,
        asset_description: Option<String>,
        asset_type: crate::models::AssetType,
        asset_type_additional_description: Option<String>,
        asset_days_requested_count: i32,
        asset_ownership_type: Option<String>,
    ) -> CreditFreddieMacAssetDetailVoe25 {
        CreditFreddieMacAssetDetailVoe25 {
            asset_unique_identifier,
            asset_account_identifier,
            asset_as_of_date,
            asset_description,
            asset_type,
            asset_type_additional_description,
            asset_days_requested_count,
            asset_ownership_type,
        }
    }
}
