/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditFreddieMacPartyVoa24 : A collection of information about a single party to a transaction. Included direct participants like the borrower and seller as well as indirect participants such as the flood certificate provider.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct CreditFreddieMacPartyVoa24 {
    #[serde(rename = "INDIVIDUAL")]
    pub individual: crate::models::CreditFreddieMacPartyIndividualVoa24,
    #[serde(rename = "ROLES")]
    pub roles: crate::models::Roles,
    #[serde(rename = "TAXPAYER_IDENTIFIERS")]
    pub taxpayer_identifiers: crate::models::TaxpayerIdentifiers,
}

impl CreditFreddieMacPartyVoa24 {
    /// A collection of information about a single party to a transaction. Included direct participants like the borrower and seller as well as indirect participants such as the flood certificate provider.
    pub fn new(
        individual: crate::models::CreditFreddieMacPartyIndividualVoa24,
        roles: crate::models::Roles,
        taxpayer_identifiers: crate::models::TaxpayerIdentifiers,
    ) -> CreditFreddieMacPartyVoa24 {
        CreditFreddieMacPartyVoa24 {
            individual,
            roles,
            taxpayer_identifiers,
        }
    }
}
