/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FdxfiAttribute : Financial Institution provider-specific attribute

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct FdxfiAttribute {
    /// Name of attribute
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Value of attribute
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl FdxfiAttribute {
    /// Financial Institution provider-specific attribute
    pub fn new() -> FdxfiAttribute {
        FdxfiAttribute {
            name: None,
            value: None,
        }
    }
}
