/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// KycCheckPhoneSummary : Result summary object specifying how the `phone` field matched.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct KycCheckPhoneSummary {
    #[serde(rename = "summary")]
    pub summary: crate::models::MatchSummaryCode,
}

impl KycCheckPhoneSummary {
    /// Result summary object specifying how the `phone` field matched.
    pub fn new(summary: crate::models::MatchSummaryCode) -> KycCheckPhoneSummary {
        KycCheckPhoneSummary { summary }
    }
}
