/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// LinkDeliveryWebhookCommunicationMethod : The communication method used to deliver the hosted link session

/// The communication method used to deliver the hosted link session
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum LinkDeliveryWebhookCommunicationMethod {
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "email")]
    Email,
}

impl ToString for LinkDeliveryWebhookCommunicationMethod {
    fn to_string(&self) -> String {
        match self {
            Self::Sms => String::from("sms"),
            Self::Email => String::from("email"),
        }
    }
}

impl Default for LinkDeliveryWebhookCommunicationMethod {
    fn default() -> LinkDeliveryWebhookCommunicationMethod {
        Self::Sms
    }
}
