/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenCreateRequestAuth : Specifies options for initializing Link for use with the Auth product. This field can be used to enable or disable extended Auth flows for the resulting Link session. Omitting any field will result in a default that can be configured by your account manager.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct LinkTokenCreateRequestAuth {
    /// Specifies whether Auth Type Select is enabled for the Link session, allowing the end user to choose between linking instantly or manually prior to selecting their financial institution. Note that this can only be true if `same_day_microdeposits_enabled` is set to true.
    #[serde(
        rename = "auth_type_select_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub auth_type_select_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Automated Micro-deposits flow.
    #[serde(
        rename = "automated_microdeposits_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub automated_microdeposits_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Instant Match flow. As of November 2022, Instant Match will be enabled by default. Instant Match can be disabled by setting this field to `false`.
    #[serde(
        rename = "instant_match_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub instant_match_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Same Day Micro-deposits flow.
    #[serde(
        rename = "same_day_microdeposits_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub same_day_microdeposits_enabled: Option<bool>,
    /// This field has been deprecated in favor of `auth_type_select_enabled`.
    #[serde(rename = "flow_type", skip_serializing_if = "Option::is_none")]
    pub flow_type: Option<FlowType>,
}

impl LinkTokenCreateRequestAuth {
    /// Specifies options for initializing Link for use with the Auth product. This field can be used to enable or disable extended Auth flows for the resulting Link session. Omitting any field will result in a default that can be configured by your account manager.
    pub fn new() -> LinkTokenCreateRequestAuth {
        LinkTokenCreateRequestAuth {
            auth_type_select_enabled: None,
            automated_microdeposits_enabled: None,
            instant_match_enabled: None,
            same_day_microdeposits_enabled: None,
            flow_type: None,
        }
    }
}

/// This field has been deprecated in favor of `auth_type_select_enabled`.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum FlowType {
    #[serde(rename = "FLEXIBLE_AUTH")]
    FlexibleAuth,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::FlexibleAuth
    }
}
