/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenCreateRequestIncomeVerificationPayrollIncome : Specifies options for initializing Link for use with Payroll Income.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct LinkTokenCreateRequestIncomeVerificationPayrollIncome {
    /// The types of payroll income verification to enable for the Link session. If none are specified, then users will see both document and digital payroll income.
    #[serde(
        rename = "flow_types",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub flow_types: Option<Option<Vec<crate::models::IncomeVerificationPayrollFlowType>>>,
    /// An identifier to indicate whether the income verification Link token will be used for an update or not
    #[serde(rename = "is_update_mode", skip_serializing_if = "Option::is_none")]
    pub is_update_mode: Option<bool>,
    /// Uniquely identify a payroll income item to update with. It should only be used for update mode.
    #[serde(
        rename = "item_id_to_update",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub item_id_to_update: Option<Option<String>>,
}

impl LinkTokenCreateRequestIncomeVerificationPayrollIncome {
    /// Specifies options for initializing Link for use with Payroll Income.
    pub fn new() -> LinkTokenCreateRequestIncomeVerificationPayrollIncome {
        LinkTokenCreateRequestIncomeVerificationPayrollIncome {
            flow_types: None,
            is_update_mode: None,
            item_id_to_update: None,
        }
    }
}
