/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PhysicalDocumentCategory : The type of identity document detected in the images provided. Will always be one of the following values:    `drivers_license` - A driver's license for the associated country    `id_card` - A general national identification card, distinct from driver's licenses    `passport` - A passport for the associated country    `residence_permit_card` - An identity document permitting a foreign citizen to <em>temporarily</em> reside in the associated country    `resident_card` - An identity document permitting a foreign citizen to <em>permanently</em> reside in the associated country  Note: This value may be different from the ID type that the user selects within Link. For example, if they select \"Driver's License\" but then submit a picture of a passport, this field will say `passport`

/// The type of identity document detected in the images provided. Will always be one of the following values:    `drivers_license` - A driver's license for the associated country    `id_card` - A general national identification card, distinct from driver's licenses    `passport` - A passport for the associated country    `residence_permit_card` - An identity document permitting a foreign citizen to <em>temporarily</em> reside in the associated country    `resident_card` - An identity document permitting a foreign citizen to <em>permanently</em> reside in the associated country  Note: This value may be different from the ID type that the user selects within Link. For example, if they select \"Driver's License\" but then submit a picture of a passport, this field will say `passport`
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum PhysicalDocumentCategory {
    #[serde(rename = "drivers_license")]
    DriversLicense,
    #[serde(rename = "id_card")]
    IdCard,
    #[serde(rename = "passport")]
    Passport,
    #[serde(rename = "residence_permit_card")]
    ResidencePermitCard,
    #[serde(rename = "resident_card")]
    ResidentCard,
}

impl ToString for PhysicalDocumentCategory {
    fn to_string(&self) -> String {
        match self {
            Self::DriversLicense => String::from("drivers_license"),
            Self::IdCard => String::from("id_card"),
            Self::Passport => String::from("passport"),
            Self::ResidencePermitCard => String::from("residence_permit_card"),
            Self::ResidentCard => String::from("resident_card"),
        }
    }
}

impl Default for PhysicalDocumentCategory {
    fn default() -> PhysicalDocumentCategory {
        Self::DriversLicense
    }
}
