/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReportType : The report type. It can be `assets` or `income`.

/// The report type. It can be `assets` or `income`.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum ReportType {
    #[serde(rename = "assets")]
    Assets,
    #[serde(rename = "income")]
    Income,
}

impl ToString for ReportType {
    fn to_string(&self) -> String {
        match self {
            Self::Assets => String::from("assets"),
            Self::Income => String::from("income"),
        }
    }
}

impl Default for ReportType {
    fn default() -> ReportType {
        Self::Assets
    }
}
