/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RiskCheckPhone : Result summary object specifying values for `phone` attributes of risk check.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct RiskCheckPhone {
    #[serde(rename = "linked_services")]
    pub linked_services: Vec<crate::models::RiskCheckLinkedService>,
}

impl RiskCheckPhone {
    /// Result summary object specifying values for `phone` attributes of risk check.
    pub fn new(linked_services: Vec<crate::models::RiskCheckLinkedService>) -> RiskCheckPhone {
        RiskCheckPhone { linked_services }
    }
}
