/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ServiceProductFulfillmentIdentifier : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.

/// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    bincode::Encode,
    bincode::Decode,
)]
pub enum ServiceProductFulfillmentIdentifier {
    #[serde(rename = "VOA")]
    Voa,
    #[serde(rename = "VOETRANSACTIONS")]
    Voetransactions,
}

impl ToString for ServiceProductFulfillmentIdentifier {
    fn to_string(&self) -> String {
        match self {
            Self::Voa => String::from("VOA"),
            Self::Voetransactions => String::from("VOETRANSACTIONS"),
        }
    }
}

impl Default for ServiceProductFulfillmentIdentifier {
    fn default() -> ServiceProductFulfillmentIdentifier {
        Self::Voa
    }
}
