/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransferCapabilitiesGetRequest : Defines the request schema for `/transfer/capabilities/get`

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct TransferCapabilitiesGetRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The Plaid `access_token` for the account that will be debited or credited. Required if not using `payment_profile_token`.
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The Plaid `account_id` corresponding to the end-user account that will be debited or credited. Returned only if `account_id` was set on intent creation.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// A payment profile token associated with the Payment Profile data that is being requested.
    #[serde(
        rename = "payment_profile_token",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_profile_token: Option<String>,
}

impl TransferCapabilitiesGetRequest {
    /// Defines the request schema for `/transfer/capabilities/get`
    pub fn new() -> TransferCapabilitiesGetRequest {
        TransferCapabilitiesGetRequest {
            client_id: None,
            secret: None,
            access_token: None,
            account_id: None,
            payment_profile_token: None,
        }
    }
}
