/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransferAuthorizationUserInRequest : The legal name and other information for the account holder.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct TransferAuthorizationUserInRequest {
    /// The user's legal name.
    #[serde(rename = "legal_name")]
    pub legal_name: String,
    /// The user's phone number. In order to qualify for a guaranteed transfer, at least one of `phone_number` or `email_address` must be provided.
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// The user's email address. In order to qualify for a guaranteed transfer, at least one of `phone_number` or `email_address` must be provided.
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::TransferUserAddressInRequest>,
}

impl TransferAuthorizationUserInRequest {
    /// The legal name and other information for the account holder.
    pub fn new(legal_name: String) -> TransferAuthorizationUserInRequest {
        TransferAuthorizationUserInRequest {
            legal_name,
            phone_number: None,
            email_address: None,
            address: None,
        }
    }
}
