/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionsRecurringGetRequestOptions : An optional object to be used with the request. If specified, `options` must not be `null`.

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct TransactionsRecurringGetRequestOptions {
    /// Include the [`personal_finance_category`](https://plaid.com/docs/api/products/transactions/#transactions-get-response-transactions-personal-finance-category) object for each transaction stream in the response.  See the [`taxonomy csv file`](https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv) for a full list of personal finance categories.
    #[serde(
        rename = "include_personal_finance_category",
        skip_serializing_if = "Option::is_none"
    )]
    pub include_personal_finance_category: Option<bool>,
}

impl TransactionsRecurringGetRequestOptions {
    /// An optional object to be used with the request. If specified, `options` must not be `null`.
    pub fn new() -> TransactionsRecurringGetRequestOptions {
        TransactionsRecurringGetRequestOptions {
            include_personal_finance_category: None,
        }
    }
}
