/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpdateEntityScreeningRequestSearchTerms : Search terms for editing an entity watchlist screening

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct UpdateEntityScreeningRequestSearchTerms {
    /// ID of the associated entity program.
    #[serde(rename = "entity_watchlist_program_id")]
    pub entity_watchlist_program_id: String,
    /// The name of the organization being screened.
    #[serde(rename = "legal_name", skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<String>,
    /// The numeric or alphanumeric identifier associated with this document.
    #[serde(rename = "document_number", skip_serializing_if = "Option::is_none")]
    pub document_number: Option<String>,
    /// A valid email address.
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    /// Valid, capitalized, two-letter ISO code representing the country of this object. Must be in ISO 3166-1 alpha-2 form.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// A phone number in E.164 format.
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// An 'http' or 'https' URL (must begin with either of those).
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl UpdateEntityScreeningRequestSearchTerms {
    /// Search terms for editing an entity watchlist screening
    pub fn new(
        entity_watchlist_program_id: String,
        client_id: String,
        secret: String,
    ) -> UpdateEntityScreeningRequestSearchTerms {
        UpdateEntityScreeningRequestSearchTerms {
            entity_watchlist_program_id,
            legal_name: None,
            document_number: None,
            email_address: None,
            country: None,
            phone_number: None,
            url: None,
            client_id,
            secret,
        }
    }
}
