/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.343.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WatchlistScreeningIndividualCreateRequest : Request input for creating an individual watchlist screening

#[derive(
    Clone, Debug, PartialEq, Default, Serialize, Deserialize, bincode::Encode, bincode::Decode,
)]
pub struct WatchlistScreeningIndividualCreateRequest {
    #[serde(rename = "search_terms")]
    pub search_terms: Box<crate::models::WatchlistScreeningRequestSearchTerms>,
    /// An identifier to help you connect this object to your internal systems. For example, your database ID corresponding to this object.
    #[serde(rename = "client_user_id", skip_serializing_if = "Option::is_none")]
    pub client_user_id: Option<String>,
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl WatchlistScreeningIndividualCreateRequest {
    /// Request input for creating an individual watchlist screening
    pub fn new(
        search_terms: crate::models::WatchlistScreeningRequestSearchTerms,
    ) -> WatchlistScreeningIndividualCreateRequest {
        WatchlistScreeningIndividualCreateRequest {
            search_terms: Box::new(search_terms),
            client_user_id: None,
            client_id: None,
            secret: None,
        }
    }
}
